// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhsKC4NK_495gkosaiYlHiTuFrI2MWgE',
    appId: '1:962375412641:web:8ccc10177dc852c6e9b9e0',
    messagingSenderId: '962375412641',
    projectId: 'my-new-anamak',
    authDomain: 'my-new-anamak.firebaseapp.com',
    storageBucket: 'my-new-anamak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI42uy2Ytc-cwA3aNQA2UQYsjOZ859j10',
    appId: '1:962375412641:android:65b4934d8d613c63e9b9e0',
    messagingSenderId: '962375412641',
    projectId: 'my-new-anamak',
    storageBucket: 'my-new-anamak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-k7nxXH9i_m9gY6G_vJPI0qnzs_Jug5A',
    appId: '1:962375412641:ios:7d32af87076552c2e9b9e0',
    messagingSenderId: '962375412641',
    projectId: 'my-new-anamak',
    storageBucket: 'my-new-anamak.appspot.com',
    iosClientId: '962375412641-a1tv4ke88ti917v970omrblgleet49ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.anamakTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-k7nxXH9i_m9gY6G_vJPI0qnzs_Jug5A',
    appId: '1:962375412641:ios:7d32af87076552c2e9b9e0',
    messagingSenderId: '962375412641',
    projectId: 'my-new-anamak',
    storageBucket: 'my-new-anamak.appspot.com',
    iosClientId: '962375412641-a1tv4ke88ti917v970omrblgleet49ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.anamakTwo',
  );
}
